import type { Persona } from './types';

export const PHASE1_PERSONAS: Persona[] = [
  {
    id: 'new-register-01',
    name: '李默 (尝鲜新注册)',
    roleDescription: '初次了解产品的新用户，通过验证码注册后尚未开始测评。',
    traits: {
      skepticism: 0.3,
      introspection: 0.5,
      stressLevel: 0.2,
      defensiveness: 0.4,
      verbosity: 'short',
      preferredThemeLens: 'emotion',
    },
    goal: 'register-only',
  },
  {
    id: 'dropoff-q02',
    name: '张扬 (答题即刻流失)',
    roleDescription: '注意力易分散的用户，刚完成第 1 题在看到第 2 题时被打断退出。',
    traits: {
      skepticism: 0.6,
      introspection: 0.3,
      stressLevel: 0.7,
      defensiveness: 0.5,
      verbosity: 'short',
      preferredThemeLens: 'workplace',
    },
    goal: 'assessment-dropoff',
    dropoffQuestionOrdinal: 2,
  },
  {
    id: 'dropoff-q05',
    name: '周思远 (中期犹豫流失)',
    roleDescription: '回答到第 4 题后在第 5 题对题意产生犹豫，随后关闭页面退出。',
    traits: {
      skepticism: 0.5,
      introspection: 0.6,
      stressLevel: 0.6,
      defensiveness: 0.6,
      verbosity: 'medium',
      preferredThemeLens: 'self_evaluation',
    },
    goal: 'assessment-dropoff',
    dropoffQuestionOrdinal: 5,
  },
  {
    id: 'complete-passive',
    name: '王小敏 (顺从完成未反馈)',
    roleDescription: '平和配合型用户，完整答完全部 8 题并查看画像结果，不提交主动反馈。',
    traits: {
      skepticism: 0.2,
      introspection: 0.7,
      stressLevel: 0.3,
      defensiveness: 0.3,
      verbosity: 'short',
      preferredThemeLens: 'emotion',
    },
    goal: 'assessment-complete',
  },
  {
    id: 'confirm-positive',
    name: '陈清 (高度认同画像)',
    roleDescription: '内省觉察力强的用户，完整作答后对 AI 生成的画像深度共鸣，选择确认。',
    traits: {
      skepticism: 0.1,
      introspection: 0.9,
      stressLevel: 0.4,
      defensiveness: 0.2,
      verbosity: 'medium',
      preferredThemeLens: 'social',
    },
    goal: 'confirm-result',
    feedbackExplanationTemplate: '画像非常准确地捕捉到了我处理社交距离感时的心理活动。',
  },
  {
    id: 'partial-nuanced',
    name: '刘柯 (严谨思辨部分认同)',
    roleDescription: '注重边界严谨性的分析型用户，认可核心结论但补充特定情境限制。',
    traits: {
      skepticism: 0.6,
      introspection: 0.8,
      stressLevel: 0.5,
      defensiveness: 0.5,
      verbosity: 'detailed',
      preferredThemeLens: 'workplace',
    },
    goal: 'partial-result',
    feedbackExplanationTemplate: '在技术讨论时我确实偏向防御，但非工作场景并不适用这一判断。',
  },
  {
    id: 'refute-skeptic',
    name: '赵子豪 (挑剔怀疑反驳者)',
    roleDescription: '对心理测试模型持有强怀疑态度的工程师，对过度概括的结论提出反驳。',
    traits: {
      skepticism: 0.9,
      introspection: 0.6,
      stressLevel: 0.8,
      defensiveness: 0.8,
      verbosity: 'detailed',
      preferredThemeLens: 'workplace',
    },
    goal: 'refute-result',
    feedbackExplanationTemplate: '不能仅凭 2 道决策就推断我缺乏信任感，这属于过度泛化。',
    correctionText: '我只在缺乏技术设计共识时保持谨慎，并非人格层面的缺乏信任。',
  },
  {
    id: 'clarify-context',
    name: '林微 (语境依赖澄清者)',
    roleDescription: '注重上下文动态变化的用户，认为画像结论需要结合具体压力阶段进行澄清。',
    traits: {
      skepticism: 0.5,
      introspection: 0.8,
      stressLevel: 0.6,
      defensiveness: 0.4,
      verbosity: 'detailed',
      preferredThemeLens: 'relationship',
    },
    goal: 'clarify-result',
    feedbackExplanationTemplate: '这种反应仅发生在长周期高压交付期间，平日状态截然不同。',
  },
  {
    id: 'returning-multi',
    name: '孙越 (回访多轮探索者)',
    roleDescription: '高活跃核心用户，分多次登录并连续完成 2 轮不同主题测评（情绪 + 职场）。',
    traits: {
      skepticism: 0.4,
      introspection: 0.8,
      stressLevel: 0.4,
      defensiveness: 0.3,
      verbosity: 'medium',
      preferredThemeLens: 'emotion',
    },
    goal: 'returning-user',
    feedbackExplanationTemplate: '第二轮测试加深了我对自我压力响应模式的理解。',
  },
  {
    id: 'boundary-critic',
    name: '吴峰 (强边界感批评者)',
    roleDescription: '对个人边界极其敏感的用户，重点反驳边界感结论并提交高质量纠错记录。',
    traits: {
      skepticism: 0.85,
      introspection: 0.7,
      stressLevel: 0.75,
      defensiveness: 0.9,
      verbosity: 'detailed',
      preferredThemeLens: 'self_evaluation',
    },
    goal: 'refute-result',
    feedbackExplanationTemplate: '对“边界感”维度的解读存在标签化嫌疑，建议展示原始支持证据。',
    correctionText: '我的边界感是出于对双方沟通成本的保护，并非抗拒人际交流。',
  },
];

export const EXTENSION_PERSONAS_20: Persona[] = [
  {
    id: 'reg-02',
    name: '钱程 (新注册观察)',
    roleDescription: '注册后观察产品页面的普通用户。',
    traits: { skepticism: 0.4, introspection: 0.4, stressLevel: 0.3, defensiveness: 0.4, verbosity: 'short', preferredThemeLens: 'social' },
    goal: 'register-only',
  },
  {
    id: 'reg-03',
    name: '冯婷 (等待通知用户)',
    roleDescription: '注册并授权后未立即答题的用户。',
    traits: { skepticism: 0.3, introspection: 0.5, stressLevel: 0.2, defensiveness: 0.3, verbosity: 'short', preferredThemeLens: 'emotion' },
    goal: 'register-only',
  },
  {
    id: 'dropoff-q01',
    name: '蒋涛 (首题流失)',
    roleDescription: '在第 1 题就直接放弃退出的用户。',
    traits: { skepticism: 0.8, introspection: 0.2, stressLevel: 0.8, defensiveness: 0.6, verbosity: 'short', preferredThemeLens: 'workplace' },
    goal: 'assessment-dropoff',
    dropoffQuestionOrdinal: 1,
  },
  {
    id: 'dropoff-q04',
    name: '沈云 (半程流失)',
    roleDescription: '答完 3 题后在 Q04 退出的用户。',
    traits: { skepticism: 0.5, introspection: 0.5, stressLevel: 0.5, defensiveness: 0.5, verbosity: 'medium', preferredThemeLens: 'relationship' },
    goal: 'assessment-dropoff',
    dropoffQuestionOrdinal: 4,
  },
  {
    id: 'dropoff-q06',
    name: '韩雪 (尾程流失)',
    roleDescription: '答完 5 题在 Q06 退出的用户。',
    traits: { skepticism: 0.6, introspection: 0.6, stressLevel: 0.6, defensiveness: 0.5, verbosity: 'medium', preferredThemeLens: 'self_evaluation' },
    goal: 'assessment-dropoff',
    dropoffQuestionOrdinal: 6,
  },
  {
    id: 'comp-02',
    name: '杨磊 (顺利完成)',
    roleDescription: '常规完成一轮测评的用户。',
    traits: { skepticism: 0.3, introspection: 0.6, stressLevel: 0.4, defensiveness: 0.4, verbosity: 'short', preferredThemeLens: 'workplace' },
    goal: 'assessment-complete',
  },
  {
    id: 'comp-03',
    name: '朱琳 (快速完成)',
    roleDescription: '果断作答完成全流程的用户。',
    traits: { skepticism: 0.2, introspection: 0.7, stressLevel: 0.3, defensiveness: 0.3, verbosity: 'short', preferredThemeLens: 'emotion' },
    goal: 'assessment-complete',
  },
  {
    id: 'comp-04',
    name: '秦昊 (沉浸完成)',
    roleDescription: '认真读题并完成画像生成的学生。',
    traits: { skepticism: 0.2, introspection: 0.8, stressLevel: 0.3, defensiveness: 0.2, verbosity: 'short', preferredThemeLens: 'social' },
    goal: 'assessment-complete',
  },
  {
    id: 'comp-05',
    name: '许诺 (标准完成)',
    roleDescription: '完成职场测评的初级职员。',
    traits: { skepticism: 0.4, introspection: 0.6, stressLevel: 0.5, defensiveness: 0.4, verbosity: 'short', preferredThemeLens: 'workplace' },
    goal: 'assessment-complete',
  },
  {
    id: 'conf-02',
    name: '何洁 (高度确认)',
    roleDescription: '对情绪洞察高度共鸣的心理学爱好者。',
    traits: { skepticism: 0.1, introspection: 0.9, stressLevel: 0.3, defensiveness: 0.2, verbosity: 'medium', preferredThemeLens: 'emotion' },
    goal: 'confirm-result',
    feedbackExplanationTemplate: '画像中对我内耗场景的描述非常精准。',
  },
  {
    id: 'conf-03',
    name: '吕博 (确认画像)',
    roleDescription: '对职场关系画像选择确认的用户。',
    traits: { skepticism: 0.2, introspection: 0.8, stressLevel: 0.4, defensiveness: 0.3, verbosity: 'medium', preferredThemeLens: 'workplace' },
    goal: 'confirm-result',
    feedbackExplanationTemplate: '确认这一评估，非常符合我最近的状态。',
  },
  {
    id: 'part-02',
    name: '施文 (部分认同补充)',
    roleDescription: '认为画像在家庭场景中偏离的用户。',
    traits: { skepticism: 0.5, introspection: 0.7, stressLevel: 0.5, defensiveness: 0.5, verbosity: 'detailed', preferredThemeLens: 'relationship' },
    goal: 'partial-result',
    feedbackExplanationTemplate: '对朋友我是开放的，但对陌生人确实保持距离。',
  },
  {
    id: 'part-03',
    name: '张倩 (细化条件)',
    roleDescription: '补充自身特例情况的用户。',
    traits: { skepticism: 0.5, introspection: 0.8, stressLevel: 0.4, defensiveness: 0.4, verbosity: 'detailed', preferredThemeLens: 'social' },
    goal: 'partial-result',
    feedbackExplanationTemplate: '核心特征一致，但社交能量恢复速度比描述中更快。',
  },
  {
    id: 'refute-02',
    name: '孔明 (强烈反驳)',
    roleDescription: '认为系统对压力反应判断错误并坚决反驳。',
    traits: { skepticism: 0.9, introspection: 0.7, stressLevel: 0.8, defensiveness: 0.9, verbosity: 'detailed', preferredThemeLens: 'emotion' },
    goal: 'refute-result',
    feedbackExplanationTemplate: '系统误把理性复盘当成了情绪压抑，这是错误的。',
    correctionText: '我的冷静是深思熟虑的决策，不等于压抑负面情绪。',
  },
  {
    id: 'refute-03',
    name: '严峻 (反驳维度定义)',
    roleDescription: '对社交能量指标计算提出异议。',
    traits: { skepticism: 0.85, introspection: 0.6, stressLevel: 0.7, defensiveness: 0.8, verbosity: 'detailed', preferredThemeLens: 'social' },
    goal: 'refute-result',
    feedbackExplanationTemplate: '我不参加低效聚会不等于社交回避。',
    correctionText: '我选择高质量深度对话，而非回避社交。',
  },
  {
    id: 'clar-02',
    name: '华静 (阶段澄清)',
    roleDescription: '澄清当前只是处于考研特殊时期。',
    traits: { skepticism: 0.4, introspection: 0.8, stressLevel: 0.9, defensiveness: 0.5, verbosity: 'detailed', preferredThemeLens: 'self_evaluation' },
    goal: 'clarify-result',
    feedbackExplanationTemplate: '当前的高焦虑度是由备考事件驱动的，非日常稳态。',
  },
  {
    id: 'clar-03',
    name: '金成 (职业语境澄清)',
    roleDescription: '澄清金融行业工作性质带来的行为偏差。',
    traits: { skepticism: 0.5, introspection: 0.7, stressLevel: 0.8, defensiveness: 0.6, verbosity: 'detailed', preferredThemeLens: 'workplace' },
    goal: 'clarify-result',
    feedbackExplanationTemplate: '高风险决策模式由岗位要求决定，而非个人特质。',
  },
  {
    id: 'ret-02',
    name: '魏晨 (高频双周回访)',
    roleDescription: '每两周做一次测评持续观察自我的探索者。',
    traits: { skepticism: 0.3, introspection: 0.9, stressLevel: 0.4, defensiveness: 0.3, verbosity: 'medium', preferredThemeLens: 'relationship' },
    goal: 'returning-user',
    feedbackExplanationTemplate: '与上个月相比，我感到自己的情绪弹性有所提升。',
  },
  {
    id: 'ret-03',
    name: '陶然 (全主题打卡用户)',
    roleDescription: '完成职场、社交两个主题的连续探索者。',
    traits: { skepticism: 0.2, introspection: 0.8, stressLevel: 0.3, defensiveness: 0.2, verbosity: 'medium', preferredThemeLens: 'social' },
    goal: 'returning-user',
    feedbackExplanationTemplate: '跨维度的测评对比让我看到了自我认知的盲区。',
  },
  {
    id: 'edge-01',
    name: '苗立 (多设备边界用户)',
    roleDescription: '使用不同网络与设备登录的活跃用户。',
    traits: { skepticism: 0.4, introspection: 0.6, stressLevel: 0.5, defensiveness: 0.4, verbosity: 'short', preferredThemeLens: 'workplace' },
    goal: 'assessment-complete',
  },
];

export const ALL_30_PERSONAS: Persona[] = [...PHASE1_PERSONAS, ...EXTENSION_PERSONAS_20];

export function getPersonas(count: number, seed?: string): Persona[] {
  if (count <= 10) {
    return PHASE1_PERSONAS.slice(0, count);
  }
  const pool = [...ALL_30_PERSONAS];
  if (count >= pool.length) return pool;
  return pool.slice(0, count);
}
