// packages/core/src/dialogue/calibration-engine.ts
// [S1-active] Calibration engine for attachment-test follow-up rounds.
// Pure functions — no DB, no AI calls. Question text generation is the caller's responsibility.
// Migrated from advanceDialogueState's state-advance logic with max_turns tightened to 3.

// ─────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────

/** A single follow-up question within a calibration round */
export interface CalibrationFollowup {
  /** Follow-up question text (generated by caller/AI) */
  question: string;
  /** Target dimension being calibrated */
  dimension: string;
  /** Turn index within this round (0-based) */
  turnIndex: number;
}

/** A calibration round anchored to a specific dimension and evidence gap */
export interface CalibrationRound {
  /** The dimension being calibrated (anchor) */
  anchorDimension: string;
  /** What evidence gap triggered this calibration */
  evidenceGap: string;
  /** Follow-up questions (1-3) */
  followups: CalibrationFollowup[];
  /** Maximum follow-ups per round — always 3 */
  maxFollowups: 3;
  /** Whether the round has been terminated (answered enough or user ended) */
  terminated: boolean;
  /** Current turn count (incremented after each user response) */
  currentTurn: number;
}

/** Options for building a calibration round */
export interface CalibrationRoundOptions {
  /** Number of initial follow-ups to generate (1-3, default 1) */
  initialFollowupCount?: number;
}

// ─────────────────────────────────────────────────────────────
// Constants
// ─────────────────────────────────────────────────────────────

/** Maximum follow-ups per calibration round (tightened from original max_turns=8 to 3) */
export const MAX_CALIBRATION_FOLLOWUPS = 3 as const;

/** Minimum follow-ups per calibration round */
export const MIN_CALIBRATION_FOLLOWUPS = 1 as const;

// ─────────────────────────────────────────────────────────────
// Functions
// ─────────────────────────────────────────────────────────────

/**
 * Build a calibration round for a given dimension and evidence gap.
 * Pure function — generates the round structure; actual question text
 * comes from the caller (AI layer provides questions).
 *
 * - maxFollowups is always 3 (tightened from original advanceDialogueState max_turns)
 * - Round starts with 1-3 follow-up slots (placeholder questions), terminated=false
 *
 * @throws Error if anchorDimension or evidenceGap is empty
 * @throws Error if initialFollowupCount is outside [1, 3]
 */
export function buildCalibrationRound(
  anchorDimension: string,
  evidenceGap: string,
  options?: CalibrationRoundOptions,
): CalibrationRound {
  if (!anchorDimension || anchorDimension.trim() === '') {
    throw new Error('anchorDimension must be a non-empty string');
  }
  if (!evidenceGap || evidenceGap.trim() === '') {
    throw new Error('evidenceGap must be a non-empty string');
  }

  const count = options?.initialFollowupCount ?? MIN_CALIBRATION_FOLLOWUPS;

  if (count < MIN_CALIBRATION_FOLLOWUPS || count > MAX_CALIBRATION_FOLLOWUPS) {
    throw new Error(
      `initialFollowupCount must be between ${MIN_CALIBRATION_FOLLOWUPS} and ${MAX_CALIBRATION_FOLLOWUPS}, got ${count}`,
    );
  }

  const followups: CalibrationFollowup[] = [];
  for (let i = 0; i < count; i++) {
    followups.push({
      question: '', // Placeholder — caller fills with AI-generated text
      dimension: anchorDimension,
      turnIndex: i,
    });
  }

  return {
    anchorDimension,
    evidenceGap,
    followups,
    maxFollowups: 3,
    terminated: false,
    currentTurn: 0,
  };
}

/**
 * Advance the calibration round by one turn (after user responds).
 * Returns a new round object with:
 * - currentTurn incremented
 * - terminated=true if currentTurn >= maxFollowups
 *
 * Max turns = 3 (stricter than the old advanceDialogueState which had max_turns=8).
 * This is an immutable operation — returns a new object.
 *
 * If the round is already terminated, returns it unchanged.
 */
export function advanceCalibrationRound(round: CalibrationRound): CalibrationRound {
  if (round.terminated) {
    return round;
  }

  const nextTurn = round.currentTurn + 1;
  const shouldTerminate = nextTurn >= round.maxFollowups;

  return {
    ...round,
    currentTurn: nextTurn,
    terminated: shouldTerminate,
  };
}

/**
 * Check if a calibration round should terminate.
 * Conditions: currentTurn >= maxFollowups OR explicitly terminated.
 */
export function isCalibrationComplete(round: CalibrationRound): boolean {
  return round.terminated || round.currentTurn >= round.maxFollowups;
}
